spring.application.name=WishList


# DATABASE CONFIG
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA/Hibernate Properties

logging.level.root=error
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
logging.level.RequestLogger=DEBUG
spring.main.banner-mode=off
jwt.secret=${JWT_SECRET}
jwt.expire=${JWT_EXPIRE}

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect